# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameView.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 793)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gameLogo = QtWidgets.QLabel(self.centralwidget)
        self.gameLogo.setGeometry(QtCore.QRect(390, 60, 361, 191))
        self.gameLogo.setText("")
        self.gameLogo.setPixmap(QtGui.QPixmap(":/Images/Logo.png"))
        self.gameLogo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gameLogo.setObjectName("gameLogo")
        self.PVPImage = QtWidgets.QLabel(self.centralwidget)
        self.PVPImage.setGeometry(QtCore.QRect(60, 170, 221, 151))
        self.PVPImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PVPImage.setStyleSheet("image: url(:/Images/PVP.png);")
        self.PVPImage.setText("")
        self.PVPImage.setObjectName("PVPImage")
        self.PVCImage = QtWidgets.QLabel(self.centralwidget)
        self.PVCImage.setGeometry(QtCore.QRect(90, 350, 231, 151))
        self.PVCImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PVCImage.setStyleSheet("image: url(:/Images/PVC.png);")
        self.PVCImage.setText("")
        self.PVCImage.setObjectName("PVCImage")
        self.CVCImage = QtWidgets.QLabel(self.centralwidget)
        self.CVCImage.setGeometry(QtCore.QRect(30, 510, 301, 231))
        self.CVCImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CVCImage.setStyleSheet("image: url(:/Images/CVC.png);")
        self.CVCImage.setText("")
        self.CVCImage.setObjectName("CVCImage")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(375, 360, 311, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gobblet"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Hello"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Hi"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
import Images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
